export const ROUTES = {
  HOME: '/',
  SOBRE: '/sobre',
  AGENDA: '/agenda',
  CONVOCATORIAS: '/convocatorias',
  SIDE_EVENTS: '/side-events',
  VIAJE_SEDE: '/datos-utiles-y-logistica',
  BECAS: '/becas',
  COMUNIDAD: '/comunidad',
  CODIGO_CONDUCTA: '/codigo-conducta',
  PRENSA: '/prensa',
  ALIADOS: '/aliados',
  CONTACTO: '/contacto',
  NOTICIAS: '/noticias',
  BLOG_DETAIL: '/noticias/:slug',
} as const;
